<a href="https://colab.research.google.com/github/starsyntaxx/nigeria-car-price-prediction/blob/main/notebooks/01_EDA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
import zipfile

zip_path = '/content/drive/MyDrive/ML PROJECTS/nigeria-car-price-prediction/data/raw/nigeria_car_data.zip'

extract_path = '/content/drive/MyDrive/ML PROJECTS/nigeria-car-price-prediction/data/raw/'

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

In [5]:
import os

os.listdir(extract_path)

['nigeria_car_data.zip', 'vroomvroom.csv']

In [6]:
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/ML PROJECTS/nigeria-car-price-prediction/data/raw/vroomvroom.csv')

df.head()

,Unnamed: 0,Make,Model,Year of Manufacture,Color,Price,Location,Trim,Drivetrain,Engine Size,Number of Cylinders,Horse Power,Interior Color,Seats,Registered Car,Second Condition,Body,Exchange Possible,VIN Chassis number
0,0,Mercedes-Benz,C180,2000,Blue,4000000.0,Kano,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,Mercedes-Benz,E350,2014,Black,13500000.0,Abuja,Base 4Matic Sedan AWD (3.5L 6cyl 7A),All Wheel,3500cc,6.0,302hp,Brown,5,Yes,NaN,NaN,NaN,NaN
2,2,Toyota,Sienna,2012,Black,16999999.0,Lagos,SE 8 Passenger,Front Wheel,3500cc,6.0,270hp,Black,8,No,No faults,Minivan,No,NaN
3,3,Mercedes-Benz,GLE-Class,2021,Blue,190000000.0,Lagos,AMG GLE 53 4MATIC,All Wheel,3000cc,6.0,429hp,Other,5,No,No faults,SUV,NaN,NaN
4,4,Honda,Accord,2005,Silver,2800000.0,Kaduna,2.4 Type S Automatic,Front Wheel,NaN,NaN,NaN,Black,NaN,Yes,"First owner, First registration, No faults",NaN,NaN,NaN

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1217 entries, 0 to 1216
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Unnamed: 0           1217 non-null   int64
 1   Make                 1217 non-null   object
 2   Model                1217 non-null   object
 3   Year of Manufacture  1217 non-null   int64
 4   Color                1217 non-null   object
 5   Price                1217 non-null   float64
 6   Location             1217 non-null   object
 7   Trim                 824 non-null    object
 8   Drivetrain           704 non-null    object
 9   Engine Size          705 non-null    object
 10  Number of Cylinders  763 non-null    float64
 11  Horse Power          659 non-null    object
 12  Interior Color       1020 non-null   object
 13  Seats                695 non-null    object
 14  Registered Car       1000 non-null   object
 15  Second Condition     1027 non-null   object
 16  Body                 730 non-null    object
 17  Exchange Possible    378 non-null    object
 18  VIN Chassis number   10 non-null     object
dtypes: float64(2), int64(2), object(15)
memory usage: 180.8+ KB

In [9]:
df.describe()

        Unnamed: 0  Year of Manufacture         Price  Number of Cylinders
count  1217.000000          1217.000000  1.217000e+03           763.000000
mean    608.000000          2013.914544  3.287482e+07             5.941022
std     351.461947             4.054026  3.521778e+07             1.119117
min       0.000000          1971.000000  2.600000e+06             3.000000
25%     304.000000          2012.000000  1.655000e+07             6.000000
50%     608.000000          2014.000000  2.630000e+07             6.000000
75%     912.000000          2016.000000  3.900000e+07             6.000000
max    1216.000000          2024.000000  5.120000e+08            12.000000

In [12]:
df.isnull().sum()

Unnamed: 0                0
Make                      0
Model                     0
Year of Manufacture       0
Color                     0
Price                     0
Location                  0
Trim                    393
Drivetrain              513
Engine Size             512
Number of Cylinders     454
Horse Power             558
Interior Color          197
Seats                   522
Registered Car          217
Second Condition        190
Body                    487
Exchange Possible       839
VIN Chassis number     1207
dtype: int64